stages:
  - build
  - deploy

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
  
build::latest:
  stage: build
  image: docker:stable-git
  only:
    - master
  script:
    - docker build --pull --force-rm=true 
        --build-arg VCS_REF=`git rev-parse --short HEAD` 
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` 
        --tag=${REGISTRY}/$(echo ${CI_PROJECT_PATH} | tr '[:upper:]' '[:lower:]') .

build::branches:
  stage: build
  image: docker:stable-git
  except:
    - master
  script:
    - docker build --pull --force-rm=true 
        --build-arg VCS_REF=`git rev-parse --short HEAD` 
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` 
        --tag=${REGISTRY}/$(echo ${CI_PROJECT_PATH} | tr '[:upper:]' '[:lower:]'):${CI_BUILD_REF_NAME} .
    
deploy::latest:
  stage: deploy
  image: docker:stable-git
  only:
    - master
  script:
    - docker push ${REGISTRY}/$(echo ${CI_PROJECT_PATH} | tr '[:upper:]' '[:lower:]')

deploy::branches:
  stage: deploy
  image: docker:stable-git
  except:
    - master
  script:
    - docker push ${REGISTRY}/$(echo ${CI_PROJECT_PATH} | tr '[:upper:]' '[:lower:]'):${CI_BUILD_REF_NAME}
