#!/usr/bin/env sh

# Docker Daemon Build Hook
# $IMAGE_NAME var is injected into the build so the tag is correct.

export DOCKERFILE_PATH=./docker/Dockerfile

docker build \
    --build-arg=BUILD_DATE="$(date +"%Y-%m-%d %H:%M:%S%:z")" \
    --build-arg=VCS_REF="$(git rev-parse --short HEAD)" \
    --build-arg=VERSION="${CACHE_TAG:-${SOURCE_BRANCH}}" \
    -t ${IMAGE_NAME} .

